<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class m_peminjaman2 extends CI_Model
{

    public $table = 'peminjaman';
    public $id = 'id_pm';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_pm,id_anggota,id_buku,tgl_pinjam,tgl_kembali');
        $this->datatables->from('peminjaman');
        //add this line for join
        //$this->datatables->join('table2', 'peminjaman.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('peminjaman2/read/$1'), 'Read') . " | " . anchor(site_url('peminjaman2/update/$1'), 'Update') . " | " . anchor(site_url('peminjaman2/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pm');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_pm', $q);
        $this->db->or_like('id_anggota', $q);
        $this->db->or_like('id_buku', $q);
        $this->db->or_like('tgl_pinjam', $q);
        $this->db->or_like('tgl_kembali', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pm', $q);
        $this->db->or_like('id_anggota', $q);
        $this->db->or_like('id_buku', $q);
        $this->db->or_like('tgl_pinjam', $q);
        $this->db->or_like('tgl_kembali', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Peminjaman_model2.php */
/* Location: ./application/models/Peminjaman_model2.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-24 16:11:05 */
/* http://harviacode.com */